### ISSUE TITLE
Exception on /api/missioncontrol/upload

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/launchpad-missioncontrol#225]
Blocking release of launchpad-template.

Release `v1` of missioncontrol is no good. :)

```
23:19:07,213 INFO  [io.openshift.appdev.missioncontrol.service.openshift.impl.fabric8.openshift.client.Fabric8OpenShiftServiceImpl] (default task-3) Setting the 'SOURCE_REPOSITORY_URL' parameter value to 'https://github.com/ALRubinger/alr-release-test.git'.
23:19:07,220 INFO  [io.openshift.appdev.missioncontrol.service.openshift.impl.fabric8.openshift.client.Fabric8OpenShiftServiceImpl] (default task-3) Setting the 'PROJECT' parameter value to 'alr-release-test'.
23:19:07,220 INFO  [io.openshift.appdev.missioncontrol.service.openshift.impl.fabric8.openshift.client.Fabric8OpenShiftServiceImpl] (default task-3) Deploying template 'pipeline' with parameters:
23:19:07,221 INFO  [io.openshift.appdev.missioncontrol.service.openshift.impl.fabric8.openshift.client.Fabric8OpenShiftServiceImpl] (default task-3) 	Application Name=alr-release-test
23:19:07,221 INFO  [io.openshift.appdev.missioncontrol.service.openshift.impl.fabric8.openshift.client.Fabric8OpenShiftServiceImpl] (default task-3) 	Source URL=https://github.com/ALRubinger/alr-release-test.git
23:19:07,306 ERROR [io.undertow.request] (default task-3) UT005023: Exception handling request to /api/missioncontrol/upload: org.jboss.resteasy.spi.UnhandledException: java.lang.NoSuchMethodError: okio.BufferedSource.rangeEquals(JLokio/ByteString;)Z
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:77)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:220)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:175)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:418)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: okio.BufferedSource.rangeEquals(JLokio/ByteString;)Z
	at okhttp3.internal.Util.bomAwareCharset(Util.java:412)
	at okhttp3.ResponseBody.string(ResponseBody.java:173)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.createStatus(OperationSupport.java:294)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:271)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:241)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:234)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:230)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:745)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:194)
	at io.fabric8.kubernetes.api.Controller.applyImageStream(Controller.java:920)
	at io.fabric8.kubernetes.api.Controller.applyEntity(Controller.java:266)
	at io.fabric8.kubernetes.api.Controller.applyList(Controller.java:985)
	at io.fabric8.kubernetes.api.Controller.apply(Controller.java:223)
	at io.openshift.appdev.missioncontrol.service.openshift.impl.fabric8.openshift.client.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:255)
	at io.openshift.appdev.missioncontrol.service.openshift.impl.fabric8.openshift.client.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:164)
	at io.openshift.appdev.missioncontrol.core.impl.MissionControlImpl.launch(MissionControlImpl.java:99)
	at io.openshift.appdev.missioncontrol.web.api.MissionControlResource.upload(MissionControlResource.java:145)
	at io.openshift.appdev.missioncontrol.web.api.MissionControlResource$Proxy$_$$_WeldSubclass.upload(Unknown Source)
	at io.openshift.appdev.missioncontrol.web.api.MissionControlResource$Proxy$_$$_WeldClientProxy.upload(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	... 42 more
```

**Comment by ALRubinger** [comment]
To repro: Process this template in Minishift, run the Launchpad, then try to select the Vertx HTTP Booster

```
kind: Template
apiVersion: v1
metadata:
  name: launchpad
  annotations:
    openshift.io/display-name: "Launchpad (Frontend + Backend + Mission Control)"
    description: This application consists of the combination of Mission Control and the Backend and Frontend
    tags: instant-app,launchpad
    iconClass: icon-shadowman
    template.openshift.io/long-description: This application consists of the combination of Mission Control, Backend and Frontend
    template.openshift.io/provider-display-name: Red Hat, Inc.
    template.openshift.io/documentation-url: https://github.com/openshiftio
    template.openshift.io/support-url: https://access.redhat.com
message: "The following service(s) have been created in your project: mission-control, launchpad-backend, launchpad-frontend.\n\nFor more information about using this template, including OpenShift considerations, see https://github.com/openshiftio"
labels:
  template: launchpad
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: launchpad-missioncontrol
    name: launchpad-missioncontrol
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: launchpad-missioncontrol
      deploymentconfig: launchpad-missioncontrol
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: launchpad-missioncontrol
    name: launchpad-missioncontrol
  spec:
    dockerImageRepository: openshiftio/launchpad-missioncontrol
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: launchpad-missioncontrol
    name: launchpad-missioncontrol
  spec:
    replicas: 1
    selector:
      app: launchpad-missioncontrol
      deploymentconfig: launchpad-missioncontrol
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: launchpad-missioncontrol
          deploymentconfig: launchpad-missioncontrol
      spec:
        containers:
        - env:
          - name: LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_API_URL
            value: ${LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_API_URL}
          - name: LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL
            value: ${LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL}
          - name: LAUNCHPAD_MISSIONCONTROL_GITHUB_USERNAME
            value: ${LAUNCHPAD_MISSIONCONTROL_GITHUB_USERNAME}
          - name: LAUNCHPAD_MISSIONCONTROL_GITHUB_TOKEN
            value: ${LAUNCHPAD_MISSIONCONTROL_GITHUB_TOKEN}
          - name: LAUNCHPAD_KEYCLOAK_URL
            value: ${LAUNCHPAD_KEYCLOAK_URL}
          - name: LAUNCHPAD_KEYCLOAK_REALM
            value: ${LAUNCHPAD_KEYCLOAK_REALM}
          - name: LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_USERNAME
            value: ${LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_USERNAME}
          - name: LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_PASSWORD
            value: ${LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_PASSWORD}
          image: ""
          imagePullPolicy: Always
          name: launchpad-missioncontrol
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: 8080
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /api/health/ready
              port: 8080
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - launchpad-missioncontrol
        from:
          kind: ImageStreamTag
          name: launchpad-missioncontrol:v1
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    labels:
      app: launchpad-missioncontrol
    name: launchpad-missioncontrol
  spec:
    to:
      kind: Service
      name: launchpad-missioncontrol
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      service: launchpad-backend
    name: launchpad-backend
  spec:
    ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      service: launchpad-backend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: launchpad-backend
    generation: 1
  spec:
    replicas: 1
    selector:
      service: launchpad-backend
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: launchpad-backend
      spec:
        containers:
        - env:
          - name: LAUNCHPAD_BACKEND_CATALOG_GIT_REPOSITORY
            value: ${LAUNCHPAD_BACKEND_CATALOG_GIT_REPOSITORY}
          - name: LAUNCHPAD_BACKEND_CATALOG_GIT_REF
            value: ${LAUNCHPAD_BACKEND_CATALOG_GIT_REF}
          - name: LAUNCHPAD_BACKEND_CATALOG_INDEX_PERIOD
            value: ${LAUNCHPAD_BACKEND_CATALOG_INDEX_PERIOD}
          image: openshiftio/launchpad-backend:1
          imagePullPolicy: Always
          name: launchpad-backend
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: launchpad-backend
    creationTimestamp: null
  spec:
    to:
      kind: Service
      name: launchpad-backend
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      service: launchpad-frontend
    name: launchpad-frontend
    annotations:
      service.alpha.openshift.io/dependencies: "[{\"name\":\"launchpad-backend\",\"namespace\":\"\",\"kind\":\"Service\"},{\"name\":\"launchpad-missioncontrol\",\"namespace\":\"\",\"kind\":\"Service\"}]"
  spec:
    ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      service: launchpad-frontend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: launchpad-frontend
    generation: 1
  spec:
    replicas: 1
    selector:
      service: launchpad-frontend
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: launchpad-frontend
      spec:
        containers:
        - image: openshiftio/launchpad-frontend:1
          imagePullPolicy: Always
          name: launchpad-frontend
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: LAUNCHPAD_BACKEND_URL
            value: ${LAUNCHPAD_BACKEND_URL}
          - name: LAUNCHPAD_KEYCLOAK_URL
            value: ${LAUNCHPAD_KEYCLOAK_URL}
          - name: LAUNCHPAD_KEYCLOAK_REALM
            value: ${LAUNCHPAD_KEYCLOAK_REALM}
          resources: {}
          terminationMessagePath: /dev/termination-log
          readinessProbe:
            httpGet:
              path: /wizard
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /wizard
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
        restartPolicy: Always
        dnsPolicy: ClusterFirst
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    name: launchpad-frontend
  spec:
    to:
      kind: Service
      name: launchpad-frontend
      weight: 100
    wildcardPolicy: None
parameters:
- description: Your GitHub username
  displayName: Your GitHub username
  name: LAUNCHPAD_MISSIONCONTROL_GITHUB_USERNAME
- description: Your GitHub Mission Control access token
  displayName: Your GitHub Mission Control access token
  name: LAUNCHPAD_MISSIONCONTROL_GITHUB_TOKEN
- description: The base URL of the OpenShift Console you are running this on
    (ie. https://hostname:port or https://ipaddress:port). Look at this page's
    address bar of your browser for the URL if you don't know it.
  displayName: Local OpenShift API URL
  name: LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_API_URL
  required: true
  value: https://openshift.default.svc.cluster.local
- description: The base URL of the OpenShift Console where the launched boosters
    should be created (ie. https://hostname:port or https://ipaddress:port).
  displayName: Target OpenShift Console URL
  name: LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL
  required: true
  value: https://$HOSTNAMEORIP:8443
- description: OpenShift user name
  displayName: OpenShift user name
  name: LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_USERNAME
  value: developer
- description: OpenShift password
  displayName: OpenShift password
  name: LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_PASSWORD
  value: developer
- description: The URL (with the /auth part) of a Keycloak installation to perform SSO authentication
  displayName: KeyCloak URL
  name: LAUNCHPAD_KEYCLOAK_URL
  value: https://sso.prod-preview.openshift.io/auth
- description: The keycloak realm to be used
  displayName: KeyCloak Realm
  name: LAUNCHPAD_KEYCLOAK_REALM
  value: fabric8
- description: The GitHub repository containing the booster catalog
  displayName: Catalog Git Repository
  name: LAUNCHPAD_BACKEND_CATALOG_GIT_REPOSITORY
  required: true
  value: https://github.com/openshiftio/booster-catalog.git
- description: The Git reference to use for the above repository
  displayName: Catalog Git Reference
  name: LAUNCHPAD_BACKEND_CATALOG_GIT_REF
  required: true
  value: 1
- description: Time in minutes that the catalog will be periodically indexed ("0" means never)
  displayName: Catalog Index Period
  name: LAUNCHPAD_BACKEND_CATALOG_INDEX_PERIOD
  required: true
  value: "0"
- description: The URL where the Launchpad Backend can be reached. You have to deduce
    this yourself by taking the default value displayed in this field and replacing
    $PROJECTNAME with the actual name of the project you are adding this template to
    and also replacing $HOSTNAMEORIP with the actual hsot name or IP number of the
    OpenShift instance your are running this on.
  displayName: Launchpad Backend URL
  name: LAUNCHPAD_BACKEND_URL
  required: true
  value: http://launchpad-backend-$PROJECTNAME.$HOSTNAMEORIP.nip.io

```

**Comment by gastaldi** [comment]
Fixed in https://github.com/openshiftio/launchpad-missioncontrol/commit/c1e8fa7c9c7524faaf380b67eaf3de2deb190e2b
