### ISSUE TITLE
Transient error in not finding newly-created GitHub repos

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/launchpad-missioncontrol#226]
We already wait for up to 10 times of 3s each when waiting for new repo creation; something is broken in the logic or needs more time?

```
Caused by: java.lang.IllegalStateException: Newly-created repository ALRubinger/vertx-alr-v1 could not be found 
	at io.openshift.appdev.missioncontrol.service.github.impl.kohsuke.KohsukeGitHubServiceImpl.createRepository(KohsukeGitHubServiceImpl.java:190)
	at io.openshift.appdev.missioncontrol.core.impl.MissionControlImpl.launch(MissionControlImpl.java:94)
	at io.openshift.appdev.missioncontrol.web.api.MissionControlResource.upload(MissionControlResource.java:145)
	at io.openshift.appdev.missioncontrol.web.api.MissionControlResource$Proxy$_$$_WeldSubclass.upload(Unknown Source)
	at io.openshift.appdev.missioncontrol.web.api.MissionControlResource$Proxy$_$$_WeldClientProxy.upload(Unknown Source)
```

**Comment by ALRubinger** [comment]
Happens when "Launch on OpenShift" is pressed in the frontend; sometimes.
