### ISSUE TITLE
Transient error in creating the pipeline

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/launchpad-missioncontrol#227]
Sometimes encountered, not always:

```
Caused by: java.lang.RuntimeException: Could not create OpenShift pipeline
	at io.openshift.appdev.missioncontrol.service.openshift.impl.fabric8.openshift.client.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:266)
	at io.openshift.appdev.missioncontrol.service.openshift.impl.fabric8.openshift.client.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:164)
	at io.openshift.appdev.missioncontrol.core.impl.MissionControlImpl.launch(MissionControlImpl.java:109)
	at io.openshift.appdev.missioncontrol.web.api.MissionControlResource.lambda$upload$1(MissionControlResource.java:164)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	... 8 more
Caused by: java.lang.RuntimeException: Failed to create ProjectRequest: vertx-alr-statusmessages due Failure executing: POST at: https://192.168.42.159:8443/oapi/v1/projectrequests. Message: project "vertx-alr-statusmessages" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=project, name=vertx-alr-statusmessages, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=project "vertx-alr-statusmessages" already exists, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.api.Controller.onApplyError(Controller.java:1446)
	at io.fabric8.kubernetes.api.Controller.applyProjectRequest(Controller.java:1209)
	at io.fabric8.kubernetes.api.Controller.applyNamespace(Controller.java:1147)
	at io.fabric8.kubernetes.api.Controller.applyNamespace(Controller.java:1125)
	at io.fabric8.kubernetes.api.Controller.applyBuildConfig(Controller.java:757)
	at io.fabric8.kubernetes.api.Controller.applyEntity(Controller.java:244)
	at io.fabric8.kubernetes.api.Controller.applyList(Controller.java:985)
	at io.fabric8.kubernetes.api.Controller.apply(Controller.java:223)
	at io.openshift.appdev.missioncontrol.service.openshift.impl.fabric8.openshift.client.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:255)
```

**Comment by gastaldi** [comment]
This is needed to avoid reading stuff from ~/.kube/config: System.setProperty("kubernetes.auth.tryKubeConfig","false");
